### ISSUE TITLE
Update readme to allow for new users

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper-docker#11]
To use the `skupper-docker` command you must first build a local container:

1. Make sure the following software is installed:

* Docker
* Golang

2. Use the following command to create a local `skupper-docker` command:

```
make build-cmd
``` 

You can now use `skupper-docker`, noting that where messages mention `skupper`, substitute `skupper-docker`

**Comment by pwright** [comment]
@ajssmith Does above help?

**Comment by Aleks3050** [comment]
hi!
can I install skuper-docker to windows os?

**Comment by pwright** [comment]
@Aleks3050  I haven't tested much, but seems to work using WSL 2, see https://docs.docker.com/docker-for-windows/wsl/

**Comment by pwright** [comment]
the original issue was addressed in https://github.com/skupperproject/skupper-docker/pull/16
