### ISSUE TITLE
cannot make

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper-docker#14]
using Fedora 32 (docker is working using https://fedoramagazine.org/docker-and-fedora-32/)

$ make build-cmd

go build -ldflags="-X main.version=0.2.0"  -o skupper-docker cmd/skupper-docker/main.go
go: github.com/skupperproject/skupper-cli@v0.0.1-beta6.0.20200324084943-48caa2ab455f requires
	github.com/openshift/api@v3.9.0+incompatible: reading github.com/openshift/api/go.mod at revision v3.9.0: unknown revision v3.9.0
make: *** [Makefile:7: build-cmd] Error 1

**Comment by ajssmith** [comment]
Could you attach your go environment (e.g. $go env)

**Comment by pwright** [comment]
thanks @ajssmith attached
[go-env.txt](https://github.com/skupperproject/skupper-docker/files/5353653/go-env.txt)

**Comment by ajssmith** [comment]
Build issue should be resolved as dependencies on skupper-cli, etc. have been update.
