### ISSUE TITLE
skupper docker on ubuntu WSL2 does not start controller

### ISSUE THREAD

**Issue by hguerrero** [skupperproject/skupper-docker#26]
When issuing the `skupper-docker init` command the following error appears:

```Unable to install Skupper: Could not start controller container: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/go/src/app/controller\": stat /go/src/app/controller: no such file or directory": unknown```

**Comment by pwright** [comment]
@hguerrero I've gotten `skupper-docker init` to run, using Docker Desktop with WSL2, Docker Desktop App > General > Use the WSL 2 based engine

**Comment by pwright** [comment]
@hguerrero I think this is explained, reopen if you disagree
